# Generated by Django 6.0.6 on 2026-07-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postimage'),
    ]

    operations = [
    ]
