# Generated by Django 6.0.6 on 2026-07-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_migrate_post_images_to_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image',
        ),
    ]
