# Generated by Django 6.0.6 on 2026-07-26 16:03

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_postimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='postimage',
            name='image',
            field=models.ImageField(default='', upload_to='posts/', validators=[users.models.validate_image_size]),
            preserve_default=False,
        ),
    ]
