# Generated by Django 6.0.6 on 2026-07-27 03:30

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_image_postimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/', validators=[users.models.validate_video_size]),
        ),
    ]
