# Generated by Django 6.0.6 on 2026-07-27 03:38

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_postimage_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', validators=[users.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/'),
        ),
    ]
