# Generated by Django 6.0.6 on 2026-08-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_postimage_media_type_alter_postimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='layout',
            field=models.CharField(choices=[('carousel', 'Carousel'), ('grid', 'Grid')], default='carousel', max_length=10),
        ),
    ]
