# Generated by Django 6.0.6 on 2026-10-09 07:56

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_edited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/', validators=[users.models.validate_video_size]),
        ),
    ]
