# Generated by Django 6.0.6 on 2026-07-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='banner_position',
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
