# Generated by Django 6.0.6 on 2026-07-13 10:57

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_banner_profile_banner_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[users.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', validators=[users.models.validate_image_size]),
        ),
    ]
