# Generated by Django 6.0.6 on 2026-07-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_todotask'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TodoTask',
        ),
    ]
