# Generated by Django 6.0.6 on 2026-08-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_language_profile_theme_profile_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='timezone',
        ),
    ]
