# Generated by Django 6.0.6 on 2026-10-09 07:56

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', validators=[users.models.validate_image_size]),
        ),
    ]
