# Generated by Django 6.0.6 on 2026-10-09 07:56

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/', validators=[users.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='story',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='stories/', validators=[users.models.validate_video_size]),
        ),
    ]
