"""
Django settings for config project.
 
Generated by 'django-admin startproject' using Django 6.0.6.
 
For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/
 
For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
 
from pathlib import Path
from decouple import config
 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
 
 
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# Мастер-ключ для шифрования сообщений чата (Fernet, base64 от 32 байт).
# Если не задан — выводится из SECRET_KEY (для разработки).
# Для продакшена сгенерируй отдельный: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
CHAT_MASTER_KEY = config('CHAT_MASTER_KEY', default='')
 
# По умолчанию DEBUG=False — безопаснее. Локально явно ставь DEBUG=True в .env
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['129.101.113.88', 'localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = [
    'http://129.101.113.88',
]



if not CSRF_TRUSTED_ORIGINS:
    # Без этого за HTTPS-прокси (nginx, cloudflare и т.п.) Django принимает
    # Origin https://домен за чужой и отвечает 403 на ЛЮБОЙ POST
    # (создание поста, истории, лайк, комментарий), хотя GET-страницы открываются.
    for _host in ALLOWED_HOSTS:
        if _host == '*':
            continue
        if _host.startswith('.'):
            CSRF_TRUSTED_ORIGINS += ['https://*' + _host, 'http://*' + _host]
        elif (
            _host == 'localhost'
            or _host.startswith(('127.', '[', '::'))
            or _host.replace('.', '').isdigit()
        ):
            continue
        else:
            CSRF_TRUSTED_ORIGINS += ['https://' + _host, 'http://' + _host]

# Прокси терминирует TLS и отдаёт Django обычный http:// — без этого заголовка
# Django не знает настоящую схему (ломает CSRF и зацикливает SECURE_SSL_REDIRECT).
TRUST_PROXY = config('TRUST_PROXY', default=True, cast=bool)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if TRUST_PROXY else None
USE_X_FORWARDED_HOST = config('USE_X_FORWARDED_HOST', default=False, cast=bool)
 
 
# Application definition
 
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'posts',
    'events',
    'chat',
    'planner',
    'tasks',
    'stories'
]
 
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
 
ROOT_URLCONF = 'config.urls'
 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
 
WSGI_APPLICATION = 'config.wsgi.application'
 
 
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}
 
 
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
 
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
 
 
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
 
LANGUAGE_CODE = 'en-us'
 
TIME_ZONE = 'UTC'
 
USE_I18N = True
 
USE_TZ = True
 
 
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
 
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
 
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
 
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
 
 
# Безопасность для продакшена (HTTPS).
# В DEBUG-режиме (локальная разработка по http://127.0.0.1) не применяется.
# Если сайт пока доступен только по http — поставь в .env:
#   SECURE_SSL_REDIRECT=False
#   COOKIE_SECURE=False
COOKIE_SECURE = config('COOKIE_SECURE', default=not DEBUG, cast=bool)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=not DEBUG, cast=bool)
if not DEBUG:
    SESSION_COOKIE_SECURE = COOKIE_SECURE
    CSRF_COOKIE_SECURE = COOKIE_SECURE
    if SECURE_SSL_REDIRECT:
        SECURE_HSTS_SECONDS = 31536000
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}